### ISSUE TITLE
Error: "Class "pocketmine\network\mcpe\protocol\types\command\CommandOverload" not found" (EXCEPTION) in "plugins/LunarRanks.phar/src/lunarelly/ranks/api/command/CommandArgs" at line 56

### ISSUE THREAD

**Issue by rowdyslav** [Lunarelly/LunarRanks#6]
--- Stack trace ---
  #0 plugins/LunarRanks.phar/src/lunarelly/ranks/command/RankCommand(38): lunarelly\ranks\api\command\CommandArgs->addParameter(int 0, string[6] player, int 8)
  #1 plugins/LunarRanks.phar/src/lunarelly/ranks/LunarRanks(125): lunarelly\ranks\command\RankCommand->__construct(object lunarelly\ranks\LunarRanks#40937)
  #2 plugins/LunarRanks.phar/src/lunarelly/ranks/LunarRanks(145): lunarelly\ranks\LunarRanks->registerCommands()
  #3 pmsrc/src/plugin/PluginBase(118): lunarelly\ranks\LunarRanks->onEnable()
  #4 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #5 pmsrc/src/Server(1400): pocketmine\plugin\PluginManager->enablePlugin(object lunarelly\ranks\LunarRanks#40937)
  #6 pmsrc/src/Server(1033): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#40709)
  #7 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#6, object pocketmine\utils\MainLogger#3, string[50] C:\Users\rowdyslav\.............. ........\Server\, string[58] C:\Users\rowdyslav\.............. ........\Server\plugins\)
  #8 pmsrc/src/PocketMine(357): pocketmine\server()
  #9 pmsrc(11): require(string[94] phar://C:/Users/rowdyslav/.............. ......../Server/PocketMine-MP.phar/src/)
--- End of exception information ---

**Comment by Lunarelly** [comment]
update to latest pmmp
